# Generated by Django 4.2.7 on 2025-11-25 05:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('phonenumber', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in a valid format. Up to 15 digits allowed.', regex='^\\+?[\\d\\s\\-\\(\\)]{9,15}$')])),
                ('role', models.CharField(choices=[('Student', 'Student'), ('Parent', 'Parent'), ('Teacher', 'Teacher'), ('Admin', 'Admin')], default='Student', max_length=50)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.IntegerField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'db_table': 'class',
            },
        ),
        migrations.CreateModel(
            name='ParentRegistration',
            fields=[
                ('parent_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in a valid format. Up to 15 digits allowed.', regex='^\\+?[\\d\\s\\-\\(\\)]{9,15}$')])),
                ('parent_username', models.CharField(max_length=255, unique=True)),
                ('parent_password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Parent Registration',
                'verbose_name_plural': 'Parent Registrations',
                'db_table': 'parent_registration',
            },
        ),
        migrations.CreateModel(
            name='ParentStudentMapping',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('parent_email', models.EmailField(max_length=254)),
                ('student_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Parent Student Mapping',
                'verbose_name_plural': 'Parent Student Mappings',
                'db_table': 'parent_student_mapping',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField(unique=True)),
                ('student_username', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('parent_email', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('school', models.CharField(blank=True, max_length=150, null=True)),
                ('course_id', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'db_table': 'student_profile',
            },
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in a valid format. Up to 15 digits allowed.', regex='^\\+?[\\d\\s\\-\\(\\)]{9,15}$')])),
                ('student_username', models.CharField(max_length=255, unique=True)),
                ('student_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('parent_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Student Registration',
                'verbose_name_plural': 'Student Registrations',
                'db_table': 'student_registration',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in a valid format. Up to 15 digits allowed.', regex='^\\+?[\\d\\s\\-\\(\\)]{9,15}$')])),
                ('teacher_username', models.CharField(max_length=255, unique=True)),
                ('teacher_email', models.EmailField(max_length=254, unique=True)),
                ('qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('experience_years', models.IntegerField(default=0)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('teacher_password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Teacher Registration',
                'verbose_name_plural': 'Teacher Registrations',
                'db_table': 'teacher_registration',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
                'db_table': 'parent',
            },
        ),
        migrations.CreateModel(
            name='TeacherLegacy',
            fields=[
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('experience_years', models.IntegerField(default=0)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('streak_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('total_days_active', models.IntegerField(default=0)),
                ('streak_started_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.OneToOneField(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.studentregistration')),
            ],
            options={
                'verbose_name': 'User Streak',
                'verbose_name_plural': 'User Streaks',
                'db_table': 'user_streak',
            },
        ),
        migrations.CreateModel(
            name='UserCoinBalance',
            fields=[
                ('balance_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_coins', models.IntegerField(default=0)),
                ('total_earned', models.IntegerField(default=0)),
                ('total_spent', models.IntegerField(default=0)),
                ('last_transaction_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.OneToOneField(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.studentregistration')),
            ],
            options={
                'verbose_name': 'User Coin Balance',
                'verbose_name_plural': 'User Coin Balances',
                'db_table': 'user_coin_balance',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset Token',
                'verbose_name_plural': 'Password Reset Tokens',
                'db_table': 'authentication_password_reset_token',
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('badge_id', models.AutoField(primary_key=True, serialize=False)),
                ('badge_type', models.CharField(choices=[('quick_master', 'Quick Master'), ('mock_master', 'Mock Master'), ('streak_7', 'Steady Learner'), ('streak_15', 'Focused Mind'), ('streak_30', 'Learning Legend')], max_length=50)),
                ('badge_title', models.CharField(max_length=100)),
                ('badge_description', models.TextField(blank=True, null=True)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.studentregistration')),
            ],
            options={
                'verbose_name': 'User Badge',
                'verbose_name_plural': 'User Badges',
                'db_table': 'user_badge',
                'ordering': ['-earned_at'],
                'indexes': [models.Index(fields=['student_id', 'badge_type'], name='user_badge_student_e265aa_idx'), models.Index(fields=['student_id', 'earned_at'], name='user_badge_student_2aabf6_idx')],
                'unique_together': {('student_id', 'badge_type')},
            },
        ),
        migrations.CreateModel(
            name='StudentFeedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('coins_awarded', models.IntegerField(default=0)),
                ('reward_received', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.studentregistration')),
            ],
            options={
                'verbose_name': 'Student Feedback',
                'verbose_name_plural': 'Student Feedback',
                'db_table': 'student_feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student_id', 'created_at'], name='student_fee_student_9b6a5a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('class_field', models.ForeignKey(blank=True, db_column='class_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.class')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.parent')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('ranking_type', models.CharField(choices=[('overall', 'Overall'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('subject', 'Subject'), ('class', 'Class')], max_length=50)),
                ('rank', models.IntegerField()),
                ('score', models.FloatField(default=0.0)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('class_name', models.CharField(blank=True, max_length=50, null=True)),
                ('total_quizzes', models.IntegerField(default=0)),
                ('total_mock_tests', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('total_coins', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.studentregistration')),
            ],
            options={
                'verbose_name': 'Leaderboard Entry',
                'verbose_name_plural': 'Leaderboard Entries',
                'db_table': 'leaderboard_entry',
                'ordering': ['ranking_type', 'rank'],
                'indexes': [models.Index(fields=['ranking_type', 'rank'], name='leaderboard_ranking_1ba780_idx'), models.Index(fields=['student_id', 'ranking_type'], name='leaderboard_student_8c0fec_idx'), models.Index(fields=['period_start', 'period_end'], name='leaderboard_period__1c83db_idx')],
                'unique_together': {('student_id', 'ranking_type', 'period_start', 'period_end', 'subject', 'class_name')},
            },
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_date', models.DateField()),
                ('quizzes_completed', models.IntegerField(default=0)),
                ('mock_tests_completed', models.IntegerField(default=0)),
                ('quick_practices_completed', models.IntegerField(default=0)),
                ('classroom_activities', models.IntegerField(default=0)),
                ('total_study_time_minutes', models.IntegerField(default=0)),
                ('average_quiz_score', models.FloatField(default=0.0)),
                ('average_mock_test_score', models.FloatField(default=0.0)),
                ('coins_earned', models.IntegerField(default=0)),
                ('activity_summary', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.studentregistration')),
            ],
            options={
                'verbose_name': 'Daily Activity',
                'verbose_name_plural': 'Daily Activities',
                'db_table': 'daily_activity',
                'ordering': ['-activity_date'],
                'indexes': [models.Index(fields=['student_id', 'activity_date'], name='daily_activ_student_6581d5_idx'), models.Index(fields=['activity_date'], name='daily_activ_activit_99e14b_idx')],
                'unique_together': {('student_id', 'activity_date')},
            },
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('coins', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('earned', 'Earned'), ('spent', 'Spent')], max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('balance_after', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.studentregistration')),
            ],
            options={
                'verbose_name': 'Coin Transaction',
                'verbose_name_plural': 'Coin Transactions',
                'db_table': 'coin_transaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student_id', 'created_at'], name='coin_transa_student_5cb7cb_idx'), models.Index(fields=['source'], name='coin_transa_source_ce2ae1_idx')],
            },
        ),
    ]
